name: ffxe
channels:
  - conda-forge
dependencies:
  - ipykernel=6.17.0
  - pip=22.3.1
  - python=3.10.6
  - pip:
    - capstone==4.0.2
    - dill==0.3.6
    - networkx==3.0
    - pyelftools==0.29
    - pyyaml==6.0
    - unicorn==2.0.1
